theme: minima
title: Xiaoyu Yuan | Academic Portfolio
description: "A showcase of AI research, projects, and academic contributions."

# Add Navigation Menu
header_pages:
  - index.md
  - projects.md
  - publications.md
  - contact.md

collections:
  projects:
    output: true
    permalink: /projects/:name/
  publications:
    output: true
    permalink: /publications/:name/
